create table Person (
    id   int,
    name varchar(255),
    age  int
);

create table Person_AUD (
    id   int,
    rev integer not null ,
    revtype  tinyint not null,
    name varchar(255),
    age  int,
    primary key (id, rev)
);

create table Revinfo (
    rev integer generated by default as identity (start with 1),
    revtstmp bigint,
    primary key (REV)
);